/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Cristopher
 */
import javax.swing.table.DefaultTableModel;
import entidades.ReporteAtencion;
import entidades.ReporteIngresos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.ReporteLOG;
import logica.adapter.ExportadorReporte;
import logica.adapter.ReporteExcelAdapter;
import logica.adapter.ReportePdfAdapter;

public class IfrmDashboardReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmDashboardReportes
     */
    public IfrmDashboardReportes() {
        initComponents();
        inicializarFormulario();
    }

    private void inicializarFormulario() {

        cmbTipoReporte.removeAllItems();
        cmbTipoReporte.addItem("Ingresos diarios");
        cmbTipoReporte.addItem("Pacientes por especialidad");
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setRowCount(0);
        tblReporte.setModel(modelo);
        btnExportarPDF.setEnabled(false);
        btnExportarExcel.setEnabled(false);
        actualizarTarjetas();
    }

    private void cargarReporteIngresos() {
        ArrayList<ReporteIngresos> lista = ReporteLOG.obtenerReporteIngresosDiarios();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Fecha");
        modelo.addColumn("Cantidad de Pagos");
        modelo.addColumn("Total Ingresos");

        for (ReporteIngresos r : lista) {
            modelo.addRow(new Object[]{
                r.getFecha(),
                r.getCantidadPagos(),
                r.getTotalIngresos()
            });
        }
        tblReporte.setModel(modelo);
        tblReporte.setEnabled(true);
    }

    private void cargarReporteEspecialidad() {
        ArrayList<ReporteAtencion> lista = ReporteLOG.obtenerReportePacientesPorEspecialidad();
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Especialidad");
        modelo.addColumn("Cantidad de Pacientes");

        for (ReporteAtencion r : lista) {
            modelo.addRow(new Object[]{
                r.getEspecialidad(),
                r.getCantidadPacientes()
            });
        }
        tblReporte.setModel(modelo);
        tblReporte.setEnabled(true);
    }

    private void actualizarTarjetas() {
        lblIngresos.setText(String.format("S/. %.2f",
                ReporteLOG.obtenerTotalIngresos()));

        lblPagos.setText(String.valueOf(
                ReporteLOG.obtenerCantidadPagos()));

        lblBoletas.setText(String.valueOf(
                ReporteLOG.obtenerCantidadBoletas()));

        lblFacturas.setText(String.valueOf(
                ReporteLOG.obtenerCantidadFacturas()));

    }

    /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlBoletas = new javax.swing.JPanel();
        lblBoletas = new javax.swing.JLabel();
        IblTitulo2 = new javax.swing.JLabel();
        pnlPagos = new javax.swing.JPanel();
        lblPagos = new javax.swing.JLabel();
        IblTitulo4 = new javax.swing.JLabel();
        pnlFacturas = new javax.swing.JPanel();
        lblFacturas = new javax.swing.JLabel();
        IblTitulo6 = new javax.swing.JLabel();
        pnlIngresos = new javax.swing.JPanel();
        lblIngresos = new javax.swing.JLabel();
        IblTitulo8 = new javax.swing.JLabel();
        lblTipoReporte = new javax.swing.JLabel();
        cmbTipoReporte = new javax.swing.JComboBox<>();
        btnGenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        btnExportarPDF = new javax.swing.JButton();
        btnExportarExcel = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlBoletas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblBoletas.setText("0");

        IblTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblTitulo2.setText("Boletas emitidas");

        javax.swing.GroupLayout pnlBoletasLayout = new javax.swing.GroupLayout(pnlBoletas);
        pnlBoletas.setLayout(pnlBoletasLayout);
        pnlBoletasLayout.setHorizontalGroup(
            pnlBoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoletasLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnlBoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBoletasLayout.createSequentialGroup()
                        .addComponent(IblTitulo2)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBoletasLayout.createSequentialGroup()
                        .addComponent(lblBoletas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        pnlBoletasLayout.setVerticalGroup(
            pnlBoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoletasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IblTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBoletas)
                .addGap(16, 16, 16))
        );

        pnlPagos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblPagos.setText("0");

        IblTitulo4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblTitulo4.setText("Pagos registrados");

        javax.swing.GroupLayout pnlPagosLayout = new javax.swing.GroupLayout(pnlPagos);
        pnlPagos.setLayout(pnlPagosLayout);
        pnlPagosLayout.setHorizontalGroup(
            pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(IblTitulo4)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPagosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        pnlPagosLayout.setVerticalGroup(
            pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(IblTitulo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPagos)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlFacturas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblFacturas.setText("0");

        IblTitulo6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblTitulo6.setText("Facturas emitidas");

        javax.swing.GroupLayout pnlFacturasLayout = new javax.swing.GroupLayout(pnlFacturas);
        pnlFacturas.setLayout(pnlFacturasLayout);
        pnlFacturasLayout.setHorizontalGroup(
            pnlFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFacturasLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(IblTitulo6)
                .addGap(20, 20, 20))
            .addGroup(pnlFacturasLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFacturasLayout.setVerticalGroup(
            pnlFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFacturasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IblTitulo6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFacturas)
                .addGap(14, 14, 14))
        );

        pnlIngresos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblIngresos.setText("S/ 0.00");

        IblTitulo8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblTitulo8.setText("Ingresos totales");

        javax.swing.GroupLayout pnlIngresosLayout = new javax.swing.GroupLayout(pnlIngresos);
        pnlIngresos.setLayout(pnlIngresosLayout);
        pnlIngresosLayout.setHorizontalGroup(
            pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresosLayout.createSequentialGroup()
                .addGroup(pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngresosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(IblTitulo8))
                    .addGroup(pnlIngresosLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblIngresos)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlIngresosLayout.setVerticalGroup(
            pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(IblTitulo8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIngresos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTipoReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoReporte.setText("Tipo reporte");

        cmbTipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingresos diarios", "Pacientes por especialidad" }));

        btnGenerar.setText("Generar");
        btnGenerar.setToolTipText("");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReporteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReporte);

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        lblTitulo.setText("Dashboard de Reportes");

        btnExportarPDF.setText("Exportar PDF");
        btnExportarPDF.setToolTipText("");
        btnExportarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarPDFActionPerformed(evt);
            }
        });

        btnExportarExcel.setText("Exportar Excel");
        btnExportarExcel.setToolTipText("");
        btnExportarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarExcelActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.setToolTipText("");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(231, 231, 231))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(pnlIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlBoletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(btnExportarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(btnExportarExcel)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lblTipoReporte)
                        .addGap(57, 57, 57)
                        .addComponent(cmbTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(btnGenerar)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addGap(72, 72, 72))))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitulo)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlBoletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoReporte)
                            .addComponent(cmbTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenerar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportarPDF)
                    .addComponent(btnExportarExcel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        if (cmbTipoReporte.getSelectedIndex() == 0) {
            cargarReporteIngresos();
        } else {
            cargarReporteEspecialidad();
        }
        if (tblReporte.getRowCount() == 0) {

            JOptionPane.showMessageDialog(this,
                    "No existen datos para generar el reporte.",
                    "Reporte",
                    JOptionPane.INFORMATION_MESSAGE);
            btnExportarPDF.setEnabled(false);
            btnExportarExcel.setEnabled(false);
            return;
        }
        btnExportarPDF.setEnabled(true);
        btnExportarExcel.setEnabled(true);
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void tblReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReporteMouseClicked


    }//GEN-LAST:event_tblReporteMouseClicked

    private void btnExportarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPDFActionPerformed
        if (tblReporte.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay datos en la tabla para exportar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ExportadorReporte exportador = new ReportePdfAdapter();
        exportador.exportar(tblReporte, cmbTipoReporte.getSelectedItem().toString());
    }//GEN-LAST:event_btnExportarPDFActionPerformed

    private void btnExportarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarExcelActionPerformed
        if (tblReporte.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay datos en la tabla para exportar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ExportadorReporte exportador = new ReporteExcelAdapter();
        exportador.exportar(tblReporte, cmbTipoReporte.getSelectedItem().toString());
    }//GEN-LAST:event_btnExportarExcelActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblTitulo2;
    private javax.swing.JLabel IblTitulo4;
    private javax.swing.JLabel IblTitulo6;
    private javax.swing.JLabel IblTitulo8;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnExportarExcel;
    private javax.swing.JButton btnExportarPDF;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> cmbTipoReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBoletas;
    private javax.swing.JLabel lblFacturas;
    private javax.swing.JLabel lblIngresos;
    private javax.swing.JLabel lblPagos;
    private javax.swing.JLabel lblTipoReporte;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBoletas;
    private javax.swing.JPanel pnlFacturas;
    private javax.swing.JPanel pnlIngresos;
    private javax.swing.JPanel pnlPagos;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables
}
